### ISSUE TITLE
Increase spacing between props and reduce amount of props

### ISSUE THREAD

**Issue by yoep** [yoep/AutomaticRoadblock#176]
Increase the spacing between props and reduce the amount of props placed with roadblocks to reduce memory consumption.
Currently, after a few roadblocks, the game may start to lag due to the amount of props with physics being spawned.

**Comment by yoep** [comment]
Hi

Good question, as I was kind of forced a few times to stop working on it due to GTA V updates which broke my modding setup. I’ve since then also been side-tracked on some other projects in the meantime.

Unfortunately, I’ve had an accident a few weeks ago which rendered me unable to do any programming work for the upcoming weeks. 
So I won’t be able to make any progress on this in the near future.

**Comment by Officerporci** [comment]
Hi yoep, i tried to compile the solution and everything works fine, but every time i go on duty starts the JIT debugger and during pursuit every entity/object of a roadblock is indicated with a coloured arrow/indicator on it, how to compile the solution in order to have the normal plugin as you released?

![Image](https://github.com/yoep/AutomaticRoadblock/assets/146420776/0b34bb08-9110-461c-875a-b3e14064ee2d)

**Comment by yoep** [comment]
Hi

You need to compile the plugin in **release** mode.
This can be done with the following `make` target, if you used make to compile the plugin.

```bash
make build-dotnet-release
```

Otherwise, if you used **dotnet** compiler directly, you'll need to execute the following **dotnet** command for release.

```bash
dotnet build --configuration "Release" --no-restore
```

**Comment by Officerporci** [comment]
Hi again :) , i compiled in released mode and tested the plugin, i have modified the spacing value between all cones and flares to 3.0;
all works fine but, after two or three dispatched roadblocks (pursuit),  the plugin encounter this error, wich after that fail to dispatch new roadblocks.

[4/5/2024 12:18:28 AM.133] LSPD First Response: Automatic Roadblocks: [WARN] Failed to discover road node for intersection road at Position: X:-548.25 Y:-658.25 Z:32.25, Heading: 64.69862
[4/5/2024 12:18:28 AM.148] LSPD First Response: Automatic Roadblocks: [WARN] Failed to discover road node for intersection road at Position: X:-445.25 Y:-658.25 Z:30.5, Heading: 164.8459
[4/5/2024 12:18:28 AM.160] LSPD First Response: Automatic Roadblocks: [ERROR] Failed to dispatch roadblock, Model with script name ground_standing_spots couldn't be found
   at AutomaticRoadblocks.Models.ModelProvider.FindModelByScriptName[T](String scriptName) in D:\my second plugin\AR\AutomaticRoadblock\Models\ModelProvider.cs:line 71
[4/5/2024 12:18:28 AM.160] at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
[4/5/2024 12:18:28 AM.160] at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[4/5/2024 12:18:28 AM.160] at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[4/5/2024 12:18:28 AM.160] at AutomaticRoadblocks.Roadblock.AbstractPursuitRoadblock..ctor(RoadblockData roadblockData, Road street, Vehicle targetVehicle, Single targetHeading, ERoadblockFlags flags) in D:\my second plugin\AR\AutomaticRoadblock\Roadblock\AbstractPursuitRoadblock.cs:line 45
[4/5/2024 12:18:28 AM.160] at AutomaticRoadblocks.Pursuit.Level.PursuitRoadblockLevel3..ctor(PursuitRoadblockRequest request) in D:\my second plugin\AR\AutomaticRoadblock\Pursuit\Level\PursuitRoadblockLevel3.cs:line 13
[4/5/2024 12:18:28 AM.160] at AutomaticRoadblocks.Pursuit.Factory.PursuitRoadblockFactory.<>c.<.cctor>b__2_2(PursuitRoadblockRequest request) in D:\my second plugin\AR\AutomaticRoadblock\Pursuit\Factory\PursuitRoadblockFactory.cs:line 19
[4/5/2024 12:18:28 AM.160] at AutomaticRoadblocks.Roadblock.Dispatcher.RoadblockDispatcher.CreateRoadblock(Road road, Vehicle vehicle, ERoadblockLevel level, Boolean createAsPreview, Boolean spikeStripsEnabled, ERoadblockFlags flags) in D:\my second plugin\AR\AutomaticRoadblock\Roadblock\Dispatcher\RoadblockDispatcher.cs:line 328
[4/5/2024 12:18:28 AM.160] at AutomaticRoadblocks.Roadblock.Dispatcher.RoadblockDispatcher.DoRoadblockCreations(IList`1 streetNodes, Vehicle vehicle, ERoadblockLevel level, Boolean createAsPreview, DispatchOptions options) in D:\my second plugin\AR\AutomaticRoadblock\Roadblock\Dispatcher\RoadblockDispatcher.cs:line 299
[4/5/2024 12:18:28 AM.160] at AutomaticRoadblocks.Roadblock.Dispatcher.RoadblockDispatcher.DoInternalDispatch(IList`1 discoveredVehicleNodes, ERoadblockLevel level, Vehicle vehicle, DispatchOptions options) in D:\my second plugin\AR\AutomaticRoadblock\Roadblock\Dispatcher\RoadblockDispatcher.cs:line 273
[4/5/2024 12:18:28 AM.161] LSPD First Response: Automatic Roadblocks: [WARN] Pursuit manager could not dispatch a new roadblock

**Comment by yoep** [comment]
Hi 

Can you check the `lights.xml` configuration file?
As it seems the plugin is unable to load the model of `ground_standing_spots`, so it might have been updated by GTA V, or a typo was made within your update. 
You can find the game model names here: https://gta-objects.xyz/objects

I'll add an additional bug ticket to catch these issues in the future so it doesn't crash anymore.

**Comment by Officerporci** [comment]
Hi yoep, i made a mistake; i forgot to drop Automatic roadbolck data folder in lspdfr plugins folder(so all localization and xml files were missing), now i reinstalled it and the plugin works correctly. Still remain the issue of cop unidentified bug in "To do" section
